pausedmusic = 0
fadeoff = 0
global.music = 0
roomname = 523
arena = 0
global.mu = -4
music = -4
secretmusic = -4
musicID = -4
secretmusicID = -4
pillarmusicID = -4
secret = 0
secretend = 0
pillar_on_camera = 0
prevpillar_on_camera = 0
room_arr = [[rm_levelselect, mu_title, mu_medievalsecret, 0], [entrance_1, mu_entrance, mu_medievalsecret, 0], [dungeon_1, mu_dungeon, mu_dungeonsecret, 0], [dungeon_8, mu_dungeon, mu_dungeonsecret, 1], [dungeon_9, mu_dungeondepth, mu_dungeonsecret, 1], [medieval_1, mu_medievalentrance, mu_medievalsecret, 0], [medieval_2, mu_medievalentrance, mu_medievalsecret, 1], [medieval_3, mu_medievalremix, mu_medievalsecret, 1], [medieval_5, mu_medievalremix, mu_medievalsecret, 1], [medieval_6, mu_medieval, mu_medievalsecret, 1], [ruin_1, mu_ruin, mu_ruinsecret, 0], [ruin_6, mu_ruin, mu_ruinsecret, 1], [ruin_7, mu_ruinremix, mu_ruinsecret, 1], [of_1, mu_otherforest, mu_medievalsecret, 0], [space_1, mu_pinball, mu_pinballsecret, 0], [saloon_1, mu_saloon, mu_saloonsecret, 0], [forest_1, mu_forest, mu_ruinsecret, 0], [farm_2, mu_farm, mu_farmsecret, 0], [plage_entrance, mu_beach, mu_medievalsecret, 0], [street_1, mu_street, mu_medievalsecret, 0], [street_intro, mu_dungeondepth, mu_medievalsecret, 0], [street_jail, mu_jail, mu_medievalsecret, 0], [street_4, mu_street2, mu_medievalsecret, 0]]
